# Generated by Django 2.0.5 on 2018-07-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20180709_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='election.User'),
        ),
    ]
