# Generated by Django 2.0.5 on 2018-07-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20180712_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='student',
            new_name='user',
        ),
    ]
